use anyhow::Error;

fn main() -> Result<(), Error> {
    Ok(())
}
